### ISSUE TITLE
regenerate gemspec - does not include all test fixture files

### ISSUE THREAD

**Issue by cldwalker** [pengwynn/chargify#6]
Problem: tried running tests from an installed gem but the gemspec doesn't include all fixtures
Solution: Regenerate gemspec with correct list of fixture files

**Comment by pengwynn** [comment]
Fixtures can get quite big to distribute with the gem. If I want to run tests for a gem, I pull down the source from GitHub. Any reason why you need to run tests from the distributed gem?

**Comment by cldwalker** [comment]
No but most gems do ship with working tests. A note about this in the readme or gemspec wouldn't hurt.
